language: ruby
cache: bundler

before_install:
  - gem install bundler
  - bundle --version

install: bundle install --without development doc

script: bundle exec rake

env: JRUBY_OPTS="$JRUBY_OPTS --debug"

rvm:
  # Include JRuby first because it takes the longest
  - jruby-9.2.5.0
  - 2.5
  - 2.6

branches:
  only:
    - develop
